### ISSUE TITLE
Print output html page to pdf file not working?

### ISSUE THREAD

**Issue by Jianru-Lin** [tc39/ecma262#729]
Hello, everyone. I'm sorry to ask such an question. But I'm just wondering why I can't print the output html page to pdf file? I can build the output html file successfully and open it with my web browser without any problem. But when I try to print it, I got an pdf file with only one page. I found if I modify the css style of the output html file, I can walk around this problem and generate an correct pdf file with all the pages. 

I modified the ```out/ecmarkup.css``` to:

```css
body {
    display: flex;
    font-size: 18px;
    line-height: 1.5;
    font-family: Cambria, Palatino Linotype, Palatino, Liberation Serif, serif;
    padding: 0;
    color: #111;
    margin: 0;
    overflow: hidden;                       /* I deleted this line */
    height: 100%;                           /* I deleted this line */
    position:absolute;                      /* I deleted this line */
    top:0; left: 0; bottom: 0; right: 0;    /* I deleted this line */
}

#spec-container {
    height: 100%;                           /* I deleted this line */
    overflow-y: auto;                       /* I deleted this line */
    overflow-x: hidden;                     /* I deleted this line */
    display: block;
    padding-left: 20px;
    flex-basis: 66%;
    flex-shrink: 0;
    flex-grow: 1;
    box-sizing: border-box;
    will-change: transform;
}

/* I added belows */
#menu,
#menu-toggle {
  display: none !important;
}
```

I can print the page now. However the output pdf file does not have any bookmark of the contents.

Thanks.
